# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: minecraftmessage.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16minecraftmessage.proto\"\x81\x01\n\x10MinecraftMessage\x12\"\n\x0cmessage_type\x18\x01 \x01(\x0e\x32\x0c.MessageType\x12\x1d\n\x07gesture\x18\x02 \x01(\x0e\x32\x0c.GestureType\x12\x14\n\x0cx_ultrasonic\x18\x03 \x01(\x05\x12\x14\n\x0cy_ultrasonic\x18\x04 \x01(\x05*4\n\x0bMessageType\x12\x0e\n\nULTRASONIC\x10\x00\x12\x0b\n\x07GESTURE\x10\x01\x12\x08\n\x04\x42OTH\x10\x02*\xa3\x01\n\x0bGestureType\x12\x0e\n\nNO_GESTURE\x10\x00\x12\x0e\n\nLEFT_CLICK\x10\x01\x12\r\n\tLOOK_LEFT\x10\x02\x12\x0e\n\nLOOK_RIGHT\x10\x03\x12\x07\n\x03ONE\x10\x04\x12\x07\n\x03TWO\x10\x05\x12\t\n\x05THREE\x10\x06\x12\x08\n\x04\x46OUR\x10\x07\x12\x08\n\x04\x46IVE\x10\x08\x12\x08\n\x04JUMP\x10\t\x12\x0b\n\x07LOOK_UP\x10\n\x12\r\n\tLOOK_DOWN\x10\x0b\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'minecraftmessage_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGETYPE._serialized_start=158
  _MESSAGETYPE._serialized_end=210
  _GESTURETYPE._serialized_start=213
  _GESTURETYPE._serialized_end=376
  _MINECRAFTMESSAGE._serialized_start=27
  _MINECRAFTMESSAGE._serialized_end=156
# @@protoc_insertion_point(module_scope)
