# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x1a\x0cnanopb.proto\"+\n\x07Message\x12\x0b\n\x03\x66oo\x18\x01 \x01(\x05\x12\x13\n\x04temp\x18\x02 \x01(\tB\x05\x92?\x02p\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE.fields_by_name['temp']._options = None
  _MESSAGE.fields_by_name['temp']._serialized_options = b'\222?\002p\005'
  _MESSAGE._serialized_start=31
  _MESSAGE._serialized_end=74
# @@protoc_insertion_point(module_scope)
